{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adsdk.adition",
    "module": "sdk_core",
    "version": "0.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-0.9.4.aar",
          "url": "sdk_core-0.9.4.aar",
          "size": 161005,
          "sha512": "f29e4a25ab1fb451fb76d90692df4c58c511cd6ed584c3477f760372e0a6b7c9f51b30233a42eb1e14299761f4ba3e6283b2241be29bdf3d90f6bd9a5bbce506",
          "sha256": "c3342da50bf45587ea141cbdac7af9cc158af2073e37d947f4abdebad1ade88f",
          "sha1": "7b52e78c4fe065208b9e2b5b78c95fbf9ce8c965",
          "md5": "b33fb3b4499905e0fe59138443c54064"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.test.ext",
          "module": "junit-ktx",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "sdk_core-0.9.4.aar",
          "url": "sdk_core-0.9.4.aar",
          "size": 161005,
          "sha512": "f29e4a25ab1fb451fb76d90692df4c58c511cd6ed584c3477f760372e0a6b7c9f51b30233a42eb1e14299761f4ba3e6283b2241be29bdf3d90f6bd9a5bbce506",
          "sha256": "c3342da50bf45587ea141cbdac7af9cc158af2073e37d947f4abdebad1ade88f",
          "sha1": "7b52e78c4fe065208b9e2b5b78c95fbf9ce8c965",
          "md5": "b33fb3b4499905e0fe59138443c54064"
        }
      ]
    }
  ]
}
